/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const CodeSplittingLazyImport = createFileRoute('/code-splitting')()
const ReactIndexLazyImport = createFileRoute('/react/')()
const ReactHooksLazyImport = createFileRoute('/react/hooks')()

// Create/Update Routes

const CodeSplittingLazyRoute = CodeSplittingLazyImport.update({
  path: '/code-splitting',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/code-splitting.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ReactIndexLazyRoute = ReactIndexLazyImport.update({
  path: '/react/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/react/index.lazy').then((d) => d.Route))

const ReactHooksLazyRoute = ReactHooksLazyImport.update({
  path: '/react/hooks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/react/hooks.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/code-splitting': {
      id: '/code-splitting'
      path: '/code-splitting'
      fullPath: '/code-splitting'
      preLoaderRoute: typeof CodeSplittingLazyImport
      parentRoute: typeof rootRoute
    }
    '/react/hooks': {
      id: '/react/hooks'
      path: '/react/hooks'
      fullPath: '/react/hooks'
      preLoaderRoute: typeof ReactHooksLazyImport
      parentRoute: typeof rootRoute
    }
    '/react/': {
      id: '/react/'
      path: '/react'
      fullPath: '/react'
      preLoaderRoute: typeof ReactIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CodeSplittingLazyRoute,
  ReactHooksLazyRoute,
  ReactIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/code-splitting",
        "/react/hooks",
        "/react/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/code-splitting": {
      "filePath": "code-splitting.lazy.tsx"
    },
    "/react/hooks": {
      "filePath": "react/hooks.lazy.tsx"
    },
    "/react/": {
      "filePath": "react/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
